# Generated by Django 4.0.4 on 2022-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nome referente ao arquivo')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
