# Generated by Django 4.0.4 on 2022-04-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importation',
            options={'verbose_name': 'Importação', 'verbose_name_plural': 'Importações'},
        ),
    ]
