# Generated by Django 4.0.4 on 2022-04-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0002_alter_importation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importation',
            options={'verbose_name': 'Arquivo importado', 'verbose_name_plural': 'Arquivos importados'},
        ),
    ]
